"""remove slug, use public id

Revision ID: dc1eecb7036b
Revises: 852f52b7b7f6
Create Date: 2026-01-13 09:04:48.178512

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dc1eecb7036b'
down_revision: Union[str, Sequence[str], None] = '852f52b7b7f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('links_slug_key'), 'links', type_='unique')
    op.drop_column('links', 'slug')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('links', sa.Column('slug', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.create_unique_constraint(op.f('links_slug_key'), 'links', ['slug'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
